export const AR = {
  "Dashboard": "لوحة التحكم", "Job feed": "الوظائف", "CV vault": "خزنة السيرة", "Tracker": "المتابعة", "Reminders": "التذكيرات",
  "Plan & usage": "الخطة والاستخدام", "Settings": "الإعدادات", "Admin": "الإدارة", "Log out": "تسجيل الخروج", "Notifications": "الإشعارات",
  "Nothing new": "لا جديد", "You've reached your plan limit": "وصلت إلى حد خطتك", "Your data is safe. Upgrade to keep going this month.": "بياناتك آمنة. قم بالترقية للاستمرار هذا الشهر.",
  "See plans": "عرض الخطط", "reviews": "المراجعات", "tailors": "السير المخصصة", "cvs": "رفع السير", "applications": "الطلبات",
  "quick": "سريع", "Apply": "قدّم", "Maybe": "ربما", "Skip": "تجاوز", "Limit reached": "تم بلوغ الحد",
  "Open app": "افتح التطبيق", "Log in": "تسجيل الدخول", "Get started free": "ابدأ مجانًا", "Start free": "ابدأ مجانًا", "I have an account": "لدي حساب",
  "The ERP for job seekers · Saudi Arabia & GCC": "نظام إدارة البحث عن عمل · السعودية والخليج",
  "Run your job search like a project, not a lottery.": "أدِر بحثك عن عمل كمشروع، لا كيانصيب.",
  "JobPilot collects jobs from legal sources, scores each one against your real CV, tailors an honest ATS-ready CV, and keeps every application and follow-up on track.": "يجمع JobPilot الوظائف من مصادر نظامية، ويقيّم كل وظيفة مقابل سيرتك الحقيقية، ويخصص سيرة صادقة متوافقة مع أنظمة التوظيف، ويتابع كل طلب وكل متابعة.",
  "No scraping — official APIs and company feeds only": "بدون كشط — واجهات رسمية وصفحات الشركات فقط", "You approve everything before it's sent": "أنت توافق على كل شيء قبل إرساله",
  "PDPL & GDPR-ready: export or delete anytime": "متوافق مع نظام حماية البيانات: صدّر أو احذف في أي وقت", "missing": "ينقص",
  "AI job review": "مراجعة الوظيفة بالذكاء الاصطناعي", "Match score, missing skills, red flags and a clear Apply / Maybe / Skip verdict for every job.": "نسبة التطابق والمهارات الناقصة والتحذيرات وحكم واضح: قدّم / ربما / تجاوز لكل وظيفة.",
  "Tailored CVs, never invented": "سير مخصصة بلا اختلاق", "Every tailored CV is checked against your master CV. Anything not in it is flagged before you approve.": "كل سيرة مخصصة تُفحص مقابل سيرتك الأساسية، وأي معلومة غير موجودة فيها تُعلَّم قبل موافقتك.",
  "One tracker for everything": "متابعة واحدة لكل شيء", "Kanban from Saved to Offer with notes, contacts, documents and a full timeline.": "لوحة كانبان من المحفوظة حتى العرض مع الملاحظات وجهات الاتصال والمستندات وسجل كامل.",
  "Reminders that respect you": "تذكيرات تحترم وقتك", "Follow-ups, interview prep and deadlines — in your timezone, outside your quiet hours.": "المتابعات والتحضير للمقابلات والمواعيد النهائية — بتوقيتك وخارج ساعات الهدوء.",
  "Send from your own Gmail": "أرسل من Gmail الخاص بك", "Drafts and applications with your approved CV attached. Nothing is ever sent without you.": "مسودات وطلبات مرفق بها سيرتك المعتمدة. لا يُرسل شيء بدونك.",
  "Arabic & English": "العربية والإنجليزية", "Fully mirrored Arabic interface and ATS-ready CVs in either language.": "واجهة عربية كاملة من اليمين لليسار وسير متوافقة بأي لغة.",
  "Privacy policy": "سياسة الخصوصية", "Terms": "الشروط", "Continue with Google": "المتابعة عبر Google", "or": "أو",
  "Welcome back": "مرحبًا بعودتك", "Log in to continue your job search.": "سجّل الدخول لمتابعة بحثك عن عمل.", "Email": "البريد الإلكتروني", "Password": "كلمة المرور",
  "Forgot password?": "نسيت كلمة المرور؟", "New to JobPilot?": "جديد على JobPilot؟", "Create an account": "أنشئ حسابًا", "Create your account": "أنشئ حسابك",
  "Free plan — no card needed.": "خطة مجانية — لا حاجة لبطاقة.", "Full name": "الاسم الكامل", "At least 8 characters": "8 أحرف على الأقل", "Create account": "إنشاء الحساب",
  "Already have an account?": "لديك حساب؟", "Reset password": "إعادة تعيين كلمة المرور", "We'll email you a reset link.": "سنرسل لك رابطًا لإعادة التعيين.",
  "If an account exists for that email, a reset link is on its way.": "إذا كان هناك حساب بهذا البريد فسيصلك رابط إعادة التعيين.", "Send reset link": "إرسال الرابط",
  "Back to login": "العودة لتسجيل الدخول", "Password updated. Please log in.": "تم تحديث كلمة المرور. سجّل الدخول.", "Choose a new password": "اختر كلمة مرور جديدة", "Update password": "تحديث كلمة المرور",
  "Setup · 1 minute": "الإعداد · دقيقة واحدة", "Let's set up your workspace": "لنجهّز مساحة عملك", "Language": "اللغة", "Country": "الدولة", "City": "المدينة",
  "e.g. Riyadh": "مثال: الرياض", "Timezone": "المنطقة الزمنية", "Quiet hours start": "بداية ساعات الهدوء", "Quiet hours end": "نهاية ساعات الهدوء",
  "Weekly application goal": "هدف التقديم الأسبوعي", "I accept the": "أوافق على", "and": "و",
  "I consent to AI processing of my CV and job data (providers may process data outside the Kingdom; never used for training).": "أوافق على معالجة سيرتي وبيانات الوظائف بالذكاء الاصطناعي (قد تتم المعالجة خارج المملكة، ولا تُستخدم للتدريب).",
  "Send me reminders and job alerts by email (optional).": "أرسل لي التذكيرات وتنبيهات الوظائف بالبريد (اختياري).", "Continue to CV upload": "متابعة لرفع السيرة",
  "Hello, {name}": "أهلًا، {name}", "Here's where your job search stands this week.": "هذا وضع بحثك عن عمل هذا الأسبوع.", "Browse jobs": "تصفح الوظائف",
  "Upload your CV to unlock AI reviews and tailored CVs.": "ارفع سيرتك لتفعيل المراجعات والسير المخصصة.", "Upload CV": "رفع السيرة", "Applied": "تم التقديم",
  "{n} tracked in total": "{n} طلبًا إجمالًا", "Response rate": "معدل الرد", "Interview rate": "معدل المقابلات", "Weekly goal": "الهدف الأسبوعي", "Funnel": "مسار التقديم",
  "Coming up": "القادم", "No interviews or reminders scheduled.": "لا مقابلات أو تذكيرات مجدولة.", "Interview": "مقابلة", "Best sources": "أفضل المصادر",
  "Apply to a few jobs to see which sources work best.": "قدّم على بعض الوظائف لترى أي المصادر أفضل.", "Source": "المصدر", "Interviews": "المقابلات",
  "Recent AI reviews": "أحدث المراجعات", "No reviews yet": "لا مراجعات بعد", "Open a job and run an AI review.": "افتح وظيفة وشغّل المراجعة.", "No reply for a while": "لا رد منذ فترة",
  "Saved": "محفوظة", "Preparing": "قيد التحضير", "Offer": "عرض", "Rejected": "مرفوضة", "Ghosted": "بلا رد",
  "remote": "عن بُعد", "onsite": "في المقر", "hybrid": "هجين", "Add a job manually": "إضافة وظيفة يدويًا",
  "Paste the job description from LinkedIn, Bayt, a company site or anywhere else. JobPilot never crawls those sites.": "الصق وصف الوظيفة من LinkedIn أو بيت.كوم أو موقع الشركة. لا يقوم JobPilot بكشط تلك المواقع.",
  "Job link (optional)": "رابط الوظيفة (اختياري)", "Paste the full job description": "الصق وصف الوظيفة كاملًا", "Add job": "إضافة وظيفة", "Job added": "تمت إضافة الوظيفة",
  "Jobs for you": "وظائف لك", "{n} jobs match your filters": "{n} وظيفة تطابق الفلاتر", "Fetch new": "جلب الجديد", "Keywords": "الكلمات المفتاحية",
  "e.g. data analyst, SQL": "مثال: محلل بيانات، SQL", "Work mode": "نمط العمل", "Any": "الكل", "Seniority": "المستوى", "Junior": "مبتدئ", "Senior": "خبير", "Lead": "قائد فريق",
  "Manager": "مدير", "Director": "مدير عام", "Minimum salary": "الحد الأدنى للراتب", "Added by me": "أضفتها بنفسي", "AI verdict": "حكم الذكاء الاصطناعي", "Search": "بحث",
  "Save search": "حفظ البحث", "Saved searches": "عمليات البحث المحفوظة", "Save a search to get new-match alerts.": "احفظ بحثًا لتصلك تنبيهات الوظائف الجديدة.",
  "No jobs match yet": "لا توجد وظائف مطابقة بعد", "Try fewer filters, press “Fetch new”, or add a job manually.": "جرّب فلاتر أقل أو اضغط «جلب الجديد» أو أضف وظيفة يدويًا.",
  "Load more": "تحميل المزيد", "Listings via official APIs and public career feeds:": "الوظائف عبر واجهات رسمية وصفحات توظيف عامة:", "Name, e.g. Riyadh data roles": "الاسم، مثال: وظائف البيانات بالرياض",
  "Alert me about new matches": "نبّهني بالوظائف الجديدة", "Save": "حفظ", "Search saved": "تم حفظ البحث", "Fetching new jobs in the background…": "جارٍ جلب وظائف جديدة في الخلفية…",
  "Matched skills": "المهارات المطابقة", "Missing skills": "المهارات الناقصة", "Keyword gaps": "كلمات مفتاحية ناقصة", "salary": "الراتب", "visa": "التأشيرة/الجنسية", "location": "الموقع", "Why": "الأسباب",
  "Saved to tracker": "تم الحفظ في المتابعة", "Back to jobs": "العودة للوظائف", "In tracker": "في المتابعة", "Save to tracker": "حفظ في المتابعة", "View original": "عرض الأصل",
  "Apply automatically": "التقديم تلقائيًا", "Fills this employer's real application form with your saved details.": "يملأ نموذج التقديم الحقيقي لدى صاحب العمل ببياناتك المحفوظة.",
  "Preview the form first": "عاين النموذج أولًا", "Fill & submit application": "املأ وقدّم الطلب", "Edit apply profile": "عدّل بيانات التقديم",
  "We stop and ask you to finish it if the employer uses a CAPTCHA or asks for anything we can't fill.": "نتوقف ونطلب منك إكمال الطلب إذا استخدم صاحب العمل كابتشا أو طلب معلومة لا نستطيع تعبئتها.",
  "Filled": "تم تعبئة", "Needs your input": "يحتاج إدخالك", "View confirmation": "عرض التأكيد", "Application submitted": "تم تقديم الطلب",
  "Apply profile": "بيانات التقديم", "These details are filled into employer application forms when you use auto-apply.": "تُعبَّأ هذه البيانات في نماذج التقديم لدى أصحاب العمل عند استخدام التقديم التلقائي.",
  "First name": "الاسم الأول", "Last name": "اسم العائلة",
  "Attach my master CV to applications": "إرفاق سيرتي الأساسية مع الطلبات", "Preview filled": "تمت معاينة التعبئة", "Submitted": "تم التقديم",
  "Not supported": "غير مدعوم", "Failed": "فشل", "Submitted, unverified": "تم التقديم دون تأكيد",
  "AI parsing is unavailable right now.": "قراءة السيرة بالذكاء الاصطناعي غير متاحة حاليًا.",
  "CV uploaded, but AI parsing is unavailable. Fill in the details by hand.": "تم رفع السيرة، لكن القراءة بالذكاء الاصطناعي غير متاحة. أدخل التفاصيل يدويًا.",
  "Retry AI parsing": "أعد محاولة القراءة",
  "No salary benchmark is available for this role yet.": "لا يوجد متوسطات رواتب متاحة لهذه الوظيفة بعد.",
  // --- admin panel ---
  "Super admin": "المدير العام", "Admin panel": "لوحة الإدارة", "Plans": "الخطط",
  "Free trial for new users": "تجربة مجانية للمستخدمين الجدد",
  "New sign-ups get this plan for N days, then return to Free automatically. 0 = off.": "يحصل المستخدمون الجدد على هذه الخطة لمدة N يومًا، ثم يعودون تلقائيًا إلى المجانية. 0 = معطّل.",
  "Save trial": "حفظ التجربة", "Premium (admin)": "مدير (مميّز)",
  "Search email or name": "ابحث بالبريد أو الاسم", "days": "يوم", "Clear": "مسح",
  "ATS boards are public employer job feeds. Paste the board tokens (the slug in the employer's careers URL, e.g. {url}), press Test to confirm they respond, then blur the field to save. Job counts show live coverage.": "لوحات ATS هي صفحات توظيف عامة لأصحاب العمل. الصق رموز اللوحات (المقطع في رابط صفحة التوظيف، مثال: {url})، ثم اضغط «اختبار» للتأكد من استجابتها، وبعدها انقر خارج الحقل للحفظ. تُظهر أرقام الوظائف التغطية المباشرة.",
  "get key": "احصل على مفتاح", "No key needed": "لا يحتاج مفتاحًا",
  "AI providers": "مزودو الذكاء الاصطناعي",
  "Keys are encrypted at rest and never sent back to the browser.": "تُشفَّر المفاتيح عند التخزين ولا تُعاد إلى المتصفح إطلاقًا.",
  "Load models": "تحميل النماذج",
  "Needs a base URL as well as a key.": "يحتاج عنوان URL أساسيًا إضافةً إلى المفتاح.",
  "Refresh": "تحديث", "Image generation": "توليد الصور", "Save image settings": "حفظ إعدادات الصور",
  "Save models": "حفظ النماذج",
  "Response rate by weekday applied": "معدل الاستجابة حسب يوم التقديم", "Response rate by source": "معدل الاستجابة حسب المصدر",
  "of": "من", "Run evaluation": "تشغيل التقييم",
  "Cost by feature (30d)": "التكلفة حسب الميزة (30 يومًا)", "Cost by user (30d)": "التكلفة حسب المستخدم (30 يومًا)",
  "Feature": "الميزة", "Model": "النموذج", "Provider": "المزوّد", "Calls": "الطلبات", "Cached": "مخزّنة", "Cost $": "التكلفة $", "User": "المستخدم", "API key": "مفتاح API",
  "Filter action (login, export, deleted…)": "رشّح الإجراء (تسجيل دخول، تصدير، حذف…)",
  "{n} anonymised CV/job cases (EN + AR) · metrics: verdict agreement, skill recall, validator recall on seeded fake facts, Arabic agreement, cost. Grow the set in": "{n} حالة سيرة/وظيفة مجهولة الهوية (إنجليزي + عربي) · المقاييس: تطابق الحكم، استرجاع المهارات، استرجاع التحقق على حقائق وهمية مزروعة، التطابق العربي، والتكلفة. وسّع المجموعة في",
  "Riyadh skyline": "أفق الرياض", "Senior Data Analyst": "محلل بيانات أول", "Profile photo": "صورة الملف الشخصي", "Hybrid": "هجين",
  "Job description": "وصف الوظيفة", "AI review": "مراجعة الذكاء الاصطناعي", "Upload your master CV first.": "ارفع سيرتك الأساسية أولًا.", "Reviewing…": "جارٍ المراجعة…", "Run AI review": "شغّل المراجعة",
  "Tailor CV & cover letter": "تخصيص السيرة وخطاب التقديم", "Only reorders and rephrases your real experience. Every claim is checked against your master CV.": "يعيد الترتيب والصياغة لخبرتك الحقيقية فقط، وكل معلومة تُفحص مقابل سيرتك الأساسية.",
  "Writing…": "جارٍ الكتابة…", "Tailor": "خصّص", "draft": "مسودة", "approved": "معتمدة",
  "CV parsed. Review the details, then save as master.": "تمت قراءة السيرة. راجع التفاصيل ثم احفظها كسيرة أساسية.", "Master CV saved as a new version": "حُفظت السيرة الأساسية كنسخة جديدة",
  "Version restored": "تمت استعادة النسخة", "Your master CV": "سيرتك الأساسية", "The single source of truth for every AI review and tailored CV.": "المصدر الوحيد لكل مراجعة وسيرة مخصصة.",
  "Reading your CV…": "جارٍ قراءة سيرتك…", "Upload PDF / DOCX": "رفع PDF / DOCX", "Save as master": "حفظ كسيرة أساسية", "Upload your CV to get started": "ارفع سيرتك للبدء",
  "PDF or DOCX, up to 8 MB. AI extracts your experience, skills and education — you review everything.": "PDF أو DOCX حتى 8 ميجابايت. يستخرج الذكاء الاصطناعي خبراتك ومهاراتك وتعليمك — وأنت تراجع كل شيء.",
  "Versions": "النسخ", "No versions yet": "لا نسخ بعد", "master": "أساسية", "Restore": "استعادة", "Original file": "الملف الأصلي", "Restore this version": "استعادة هذه النسخة",
  "Experience": "الخبرات", "Education": "التعليم", "Projects": "المشاريع", "Languages": "اللغات", "Certifications": "الشهادات", "Add": "إضافة", "Remove": "إزالة",
  "Company": "الشركة", "Title": "المسمى", "Location": "الموقع", "Start": "البداية", "End": "النهاية", "Institution": "المؤسسة", "Degree": "الدرجة", "Field": "التخصص",
  "Name": "الاسم", "Description": "الوصف", "Language ": "اللغة", "Level": "المستوى", "Issuer": "الجهة", "Year": "السنة", "One bullet per line": "نقطة في كل سطر",
  "Headline": "المسمى المهني", "Phone": "الهاتف", "Links (comma separated)": "روابط (مفصولة بفواصل)", "Summary": "الملخص", "Skills": "المهارات", "Comma separated": "مفصولة بفواصل",
  "Master CV": "السيرة الأساسية", "Tailored version": "النسخة المخصصة", "Validation check": "فحص التحقق", "open": "مفتوحة",
  "Anything not found in your master CV is flagged. Remove it, or confirm it is true before approving.": "كل ما لا يوجد في سيرتك الأساسية يُعلَّم. أزله أو أكّد صحته قبل الاعتماد.",
  "No unsupported claims found.": "لا توجد معلومات غير مدعومة.", "It's true": "صحيح", "Undo": "تراجع", "removed": "أُزيلت", "confirmed": "مؤكدة",
  "Approved and linked to your application": "اعتُمدت وربطت بطلبك", "Back to job": "العودة للوظيفة", "Tailor studio": "استوديو التخصيص", "from master": "من الأساسية",
  "Re-check": "إعادة الفحص", "Resolve {n} flags to approve": "عالج {n} تنبيهات للاعتماد", "Approve": "اعتماد", "Changes vs master": "التغييرات مقابل الأساسية", "Edit CV": "تعديل السيرة",
  "Cover letter": "خطاب التقديم", "What the AI changed": "ما غيّره الذكاء الاصطناعي", "Approved versions are locked. Tailor again to make changes.": "النسخ المعتمدة مقفلة. خصّص مجددًا لإجراء تغييرات.", "Save edits": "حفظ التعديلات",
  "Untitled": "بدون عنوان", "Ghosted?": "بلا رد؟", "Applications": "الطلبات", "{n} applications": "{n} طلب", "Add application": "إضافة طلب", "Role": "الوظيفة", "Status": "الحالة",
  "Updated": "آخر تحديث", "No applications yet.": "لا طلبات بعد.", "Role title": "المسمى الوظيفي",
  "Application": "طلب توظيف", "Dear Hiring Team,": "فريق التوظيف المحترم،", "Please find attached my CV for the {role} role at {company}.": "مرفق سيرتي الذاتية لوظيفة {role} لدى {company}.", "Kind regards,": "مع خالص التحية،",
  "Email sent from your Gmail": "أُرسل البريد من Gmail الخاص بك", "Draft saved in your Gmail": "حُفظت المسودة في Gmail", "Gmail isn't configured on this workspace yet.": "لم يتم إعداد Gmail بعد.",
  "Gmail sending is available on Pro and Premium.": "الإرسال عبر Gmail متاح في Pro وPremium.", "Connect Gmail in Settings to send from your own account.": "اربط Gmail من الإعدادات للإرسال من حسابك.",
  "To": "إلى", "No attachment": "بدون مرفق", "Approved CV": "سيرة معتمدة", "Save as Gmail draft": "حفظ كمسودة في Gmail", "Send": "إرسال", "Send this email now?": "إرسال هذا البريد الآن؟",
  "It will be sent from {email} to {to}.": "سيُرسل من {email} إلى {to}.", "Cancel": "إلغاء", "Job & AI review": "الوظيفة والمراجعة", "No reply for a while. Mark as Ghosted?": "لا رد منذ فترة. نقلها إلى «بلا رد»؟",
  "Mark ghosted": "نقل إلى بلا رد", "Overview": "نظرة عامة", "Notes": "الملاحظات", "Contacts": "جهات الاتصال", "Documents": "المستندات", "Timeline": "السجل",
  "Interview date": "موعد المقابلة", "Follow-up date": "موعد المتابعة", "Leave empty to use your default follow-up rule.": "اتركه فارغًا لاستخدام قاعدة المتابعة الافتراضية.",
  "Application deadline": "آخر موعد للتقديم", "Salary / offer notes": "الراتب / ملاحظات العرض", "Write a note…": "اكتب ملاحظة…", "Add note": "إضافة ملاحظة", "Role ": "الدور",
  "Add contact": "إضافة جهة اتصال", "Upload file": "رفع ملف", "Open": "فتح", "Uploaded": "تم الرفع",
  "Done": "تم", "Needs action": "بحاجة لإجراء", "Upcoming": "القادمة", "Nothing here.": "لا شيء هنا.", "Follow-ups & interview prep": "المتابعات والتحضير للمقابلات",
  "Rules: follow up {n} days after applying · interview prep 24h and 1h before · deadline 2 days before.": "القواعد: متابعة بعد {n} أيام من التقديم · تحضير قبل المقابلة بـ24 ساعة وساعة · قبل الموعد النهائي بيومين.",
  "Quiet hours {a}–{b} ({tz}). Reminders due then arrive when quiet hours end.": "ساعات الهدوء {a}–{b} ({tz}). التذكيرات خلالها تصل عند انتهائها.", "No reminders yet": "لا تذكيرات بعد",
  "Move an application to Applied or set an interview date and reminders are created automatically.": "انقل طلبًا إلى «تم التقديم» أو حدّد موعد مقابلة وستُنشأ التذكيرات تلقائيًا.",
  "Custom reminder": "تذكير مخصص", "e.g. Prepare portfolio": "مثال: تجهيز ملف الأعمال", "Add reminder": "إضافة تذكير", "follow_up": "متابعة", "interview_24h": "مقابلة بعد 24 ساعة",
  "interview_1h": "مقابلة بعد ساعة", "deadline": "موعد نهائي", "custom": "مخصص", "pending": "قيد الانتظار", "sent": "أُرسل", "snoozed": "مؤجل", "done": "تم",
  "Quiet from": "الهدوء من", "Quiet until": "الهدوء حتى", "Follow up after (days)": "المتابعة بعد (أيام)", "Suggest “Ghosted” after (days)": "اقتراح «بلا رد» بعد (أيام)", "Save changes": "حفظ التغييرات",
  "AI profile avatar": "صورة رمزية بالذكاء الاصطناعي", "Generate a professional, privacy-friendly avatar (no photo needed).": "أنشئ صورة رمزية احترافية تحفظ خصوصيتك (بدون صورة شخصية).",
  "Generate": "إنشاء", "New avatar ready": "الصورة الرمزية جاهزة", "Create drafts and send applications from your own account. Every send needs your click.": "أنشئ مسودات وأرسل طلباتك من حسابك. كل إرسال يحتاج نقرتك.",
  "Connected": "مرتبط", "Not connected — Google OAuth credentials are not configured yet": "غير مرتبط — لم تُضبط بيانات Google OAuth بعد", "Available on Pro and Premium": "متاح في Pro وPremium",
  "Not connected": "غير مرتبط", "Disconnect": "فصل", "Connect Gmail": "ربط Gmail", "Official WhatsApp Business reminders with opt-in and one-tap “done / snooze” replies.": "تذكيرات واتساب للأعمال الرسمية بموافقتك مع ردود «تم / تأجيل».",
  "Coming in Phase 2": "قريبًا في المرحلة الثانية", "Consents": "الموافقات", "AI processing of my CV": "معالجة سيرتي بالذكاء الاصطناعي", "Email reminders & job alerts": "تذكيرات وتنبيهات بالبريد",
  "WhatsApp reminders (Phase 2)": "تذكيرات واتساب (المرحلة 2)", "Gmail inbox scanning (Phase 2)": "فحص صندوق Gmail (المرحلة 2)", "Consent history": "سجل الموافقات",
  "Export my data": "تصدير بياناتي", "Everything you own as JSON, including your files.": "كل بياناتك بصيغة JSON مع ملفاتك.", "Export": "تصدير", "Delete my account": "حذف حسابي",
  "Permanently deletes your CVs, files, applications and connected accounts.": "يحذف نهائيًا سيرك وملفاتك وطلباتك وحساباتك المرتبطة.", "Delete": "حذف", "Delete account permanently?": "حذف الحساب نهائيًا؟",
  "Type DELETE to confirm. This cannot be undone.": "اكتب DELETE للتأكيد. لا يمكن التراجع.", "Delete forever": "حذف نهائي", "Gmail connected": "تم ربط Gmail", "Gmail connection failed": "فشل ربط Gmail",
  "Profile": "الملف الشخصي", "Integrations": "التكاملات", "Privacy & data": "الخصوصية والبيانات",
  "Unlimited": "غير محدود", "Payment confirmed — plan upgraded": "تم الدفع — تمت ترقية الخطة", "Online payments are not activated yet. Contact the admin to upgrade.": "الدفع الإلكتروني غير مفعّل بعد. تواصل مع المشرف للترقية.",
  "Usage resets on the 1st of each month. Hitting a limit never deletes your data.": "يُعاد ضبط الاستخدام أول كل شهر، وبلوغ الحد لا يحذف بياناتك.", "AI job reviews": "مراجعات الوظائف",
  "Tailored CVs": "السير المخصصة", "CV uploads": "رفع السير", "Tracked applications": "الطلبات المتابعة", "Current": "الحالية", "mo": "شهر",
  "AI job reviews / month": "مراجعة وظيفة / شهر", "tailored CVs / month": "سيرة مخصصة / شهر", "tracked applications": "طلب متابع", "Email reminders": "تذكيرات بالبريد",
  "Gmail drafts & sending": "مسودات وإرسال Gmail", "Auto AI review of new matches": "مراجعة تلقائية للوظائف الجديدة", "Priority AI": "أولوية في الذكاء الاصطناعي", "Upgrade to {p}": "الترقية إلى {p}",
  "Saved ": "تم الحفظ", "employer": "جهة عمل", "title": "مسمى", "date": "تاريخ", "skill": "مهارة", "number": "رقم", "degree": "مؤهل", "claim": "ادعاء", "certification": "شهادة",
  "CV PDF": "السيرة PDF", "Prep": "التحضير", "Generate interview-prep pack": "إنشاء حزمة التحضير للمقابلة", "Regenerate prep pack": "إعادة إنشاء حزمة التحضير",
  "Likely questions with answer outlines drawn only from your real CV.": "أسئلة متوقعة مع مخططات إجابة من سيرتك الحقيقية فقط.", "Gaps to prepare": "فجوات تستعد لها",
  "Questions to ask them": "أسئلة تطرحها عليهم", "Research": "ابحث عن", "Send code": "إرسال الرمز", "6-digit code": "رمز من 6 أرقام", "Verify": "تحقق", "WhatsApp connected": "تم ربط واتساب",
  "I agree to receive JobPilot reminders on WhatsApp. Reply STOP anytime to opt out.": "أوافق على استلام تذكيرات JobPilot عبر واتساب، ويمكنني الرد بـ STOP للإيقاف.",
  "Not connected — WhatsApp Business credentials are not configured yet": "غير مرتبط — لم تُضبط بيانات واتساب للأعمال بعد", "Available on Premium": "متاح في Premium",
  "Save jobs from any site": "احفظ الوظائف من أي موقع", "Copy": "نسخ", "Copied": "تم النسخ",
  "Create a browser bookmark and paste this as its URL. On any job page, select the description (or nothing) and click the bookmark — only what you see is sent to JobPilot.": "أنشئ إشارة مرجعية في المتصفح والصق هذا كرابط لها. في أي صفحة وظيفة ظلّل الوصف ثم اضغط الإشارة — يُرسل فقط ما تراه إلى JobPilot.",
  "Coaching": "الإرشاد المهني", "Share your tracker with a career coach, or coach other candidates.": "شارك متابعتك مع مرشد مهني، أو أرشد مرشحين آخرين.", "My coaches": "مرشدوني",
  "Coaches can see your applications (not your files or contacts) and leave comments. Revoke anytime.": "يرى المرشد طلباتك (دون ملفاتك أو جهات اتصالك) ويترك تعليقات، ويمكنك الإلغاء في أي وقت.",
  "My candidates": "مرشحيّ", "Candidates who share access with you appear here.": "يظهر هنا المرشحون الذين شاركوا متابعتهم معك.", "Select a candidate": "اختر مرشحًا",
  "Review their pipeline and leave comments on specific applications.": "راجع مسار طلباته واترك تعليقات على طلبات محددة.", "Leave a comment for your candidate…": "اكتب تعليقًا للمرشح…",
  "Comment sent": "تم إرسال التعليق", "Salary benchmark": "مؤشر الرواتب", "Based on {n} listings with published salaries.": "بناءً على {n} إعلانًا بها رواتب منشورة.",
  "AI estimate (confidence: {c}). Verify with the employer.": "تقدير بالذكاء الاصطناعي (الثقة: {c}). تحقّق مع صاحب العمل.", "low": "منخفضة", "medium": "متوسطة", "high": "عالية",
  "Pay with mada, Apple Pay or STC Pay": "ادفع عبر مدى أو Apple Pay أو STC Pay", "Secure payment by Moyasar. One month of access; renew anytime.": "دفع آمن عبر ميسر. اشتراك لمدة شهر ويمكن التجديد في أي وقت.",
  "Pay in SAR with mada, Apple Pay or STC Pay. Each payment adds one month.": "ادفع بالريال عبر مدى أو Apple Pay أو STC Pay، وكل دفعة تضيف شهرًا.", "Admin accounts always use the Premium plan.": "حسابات المشرفين تستخدم خطة Premium دائمًا.",
  "Your {p} plan is active until {date}, then returns to Free.": "خطة {p} فعّالة حتى {date}، ثم تعود إلى المجانية.", "Access shared": "تمت المشاركة", "CV DOCX": "السيرة DOCX", "Cover PDF": "الخطاب PDF", "Cover DOCX": "الخطاب DOCX", "Email ": "البريد",
};
