export const COUNTRIES = [
  ["SA", "Saudi Arabia", "السعودية"], ["AE", "United Arab Emirates", "الإمارات"], ["QA", "Qatar", "قطر"],
  ["KW", "Kuwait", "الكويت"], ["BH", "Bahrain", "البحرين"], ["OM", "Oman", "عُمان"], ["EG", "Egypt", "مصر"],
  ["JO", "Jordan", "الأردن"], ["LB", "Lebanon", "لبنان"], ["IQ", "Iraq", "العراق"], ["MA", "Morocco", "المغرب"],
  ["TN", "Tunisia", "تونس"], ["TR", "Turkey", "تركيا"], ["PK", "Pakistan", "باكستان"], ["PH", "Philippines", "الفلبين"],
  ["GB", "United Kingdom", "المملكة المتحدة"], ["US", "United States", "الولايات المتحدة"],
  ["IN", "India", "الهند"], ["DE", "Germany", "ألمانيا"], ["FR", "France", "فرنسا"], ["CA", "Canada", "كندا"],
  ["AU", "Australia", "أستراليا"],
];
export const TIMEZONES = ["Asia/Riyadh", "Asia/Dubai", "Asia/Qatar", "Asia/Kuwait", "Asia/Bahrain", "Asia/Muscat", "Africa/Cairo",
  "Asia/Amman", "Asia/Beirut", "Asia/Baghdad", "Africa/Casablanca", "Africa/Tunis", "Europe/Istanbul", "Asia/Karachi",
  "Asia/Manila", "Europe/London", "Europe/Berlin", "Europe/Paris", "Asia/Kolkata", "America/New_York", "America/Toronto",
  "Australia/Sydney", "UTC"];
// Keys match the backend's CITY_INDEX in sources.py, so a suggestion here always matches the same job listings.
// Generated by backend/scripts/gen_frontend_cities.py — regenerate rather than editing by hand.
export const CITIES = {
  SA: [
       // Riyadh
       ["riyadh", "Riyadh", "الرياض"], ["al-kharj", "Al Kharj", "الخرج"], ["majmaah", "Al Majmaah", "المجمة"], ["zulfi", "Al Zulfi", "الزلف"], ["dawadmi", "Ad-Dawadmi", "الدوادمي"], ["diriyah", "Diriyah", "الدرعية"], ["afif", "Afif", "عفيف"], ["wadi-ad-dawasir", "Wadi ad-Dawasir", "وادي الدواسر"], ["thuayrat", "Thuayrat", "ثريعات"], ["najd", "Najd", "نجد"],
       // Makkah
       ["jeddah", "Jeddah", "جدة"], ["makkah", "Mecca", "مكة المكرمة"], ["taif", "Taif", "الطائف"], ["rabigh", "Rabigh", "رابغ"], ["khaybar", "Khaybar", "خيبر"], ["haradh", "Haradh", "حرض"], ["jumum", "Jumum", "جموم"], ["thawal", "Thawal", "ثول"], ["qunfudhah", "Al Qunfudhah", "القنفذة"], ["lehaj", "Lehaj", "لحج"],
       // Madinah
       ["madinah", "Medina", "المدينة المنورة"], ["yanbu", "Yanbu", "ينبع"], ["yanbu-al-bahar", "Yanbu al-Bahar", "ينبع البحر"], ["al-ula", "Al Ula", "العلا"],
       // Eastern Province
       ["dammam", "Dammam", "الدمام"], ["khobar", "Khobar", "الخبر"], ["dhahran", "Dhahran", "الظهران"], ["jubail", "Jubail", "الجبيل"], ["qatif", "Qatif", "القطيف"], ["al-ahsa", "Al Ahsa", "الأحساء"], ["hafar-al-batin", "Hafar Al Batin", "حفر الباطن"], ["ras-tanura", "Ras Tanura", "رأس تنورة"], ["khafji", "Khafji", "خفجي"], ["safha", "Safha", "الصفا"],
       // Qassim
       ["buraidah", "Buraidah", "بريدة"], ["unaizah", "Unaizah", "عنيزة"], ["ar-rass", "Ar Rass", "الراس"], ["bukayriyah", "Al Bukayriyah", "البكيرية"], ["qaryat-al-kamil", "Qaryat Al Kamil", "قرية الكامل"], ["ras-al-khair", "Ras Al Khair", "رأس الخير"], ["al-qassim", "Al Qassim", "القصيم"], ["bada", "Bad'ah", "البدا"],
       // Asir
       ["abha", "Abha", "أبها"], ["khamis-mushait", "Khamis Mushait", "خميس مشيط"], ["bisha", "Bisha", "بيشة"], ["baljurashi", "Baljurashi", "بلجرشي"], ["rany", "Rany", "رنية"], ["al-baha", "Al Bahah", "الباحة"], ["muhajjar", "Muhajjar", "محجار"], ["al-harj", "Al Harj", "الحرج"],
       // Tabuk
       ["tabuk", "Tabuk", "تبوك"], ["turayf", "Turayf", "الطارف"], ["qurayyat", "Al Qurayyat", "القريات"], ["al-wajh", "Al Wajh", "الوجه"], ["duba", "Duba", "دبة"], ["tayyibah", "Tayyibah", "طيبة"], ["tayma", "Tayma", "تيماء"],
       // Hail
       ["hail", "Hail", "حائل"], ["sakaka", "Sakaka", "سكاكا"], ["qarn-al-manazil", "Qarn Al Manazil", "قرن المنازيل"],
       // Al Jawf
       ["skaka", "Skaka", "سكا"], ["dumat-al-jandal", "Dumat Al Jandal", "دومة الجندل"],
       // Northern Borders
       ["arar", "Arar", "عرعر"], ["al-qaisumah", "Al Qaisumah", "القaisyمة"], ["rafha", "Rafha", "رفح"],
       // Jazan
       ["jazan", "Jazan", "جازان"], ["sabaya", "Sabaya", "صبيحة"], ["samhat", "Samhat", "سمهات"], ["farasan", "Farasan", "فراسان"], ["beesh", "Beesh", "بيش"],
       // Najran
       ["najran", "Najran", "نجران"], ["sharurah", "Sharurah", "شرورة"], ["damt", "Damt", "ضمت"], ["umm-al-jimal", "Umm al-Jimal", "أم الجيال"],
       // Giga projects
       ["qiddiya", "Qiddiya", "القدية"], ["amaala", "Amaala", "العمالة"],
       ],
  AE: [["dubai", "Dubai", "دبي"], ["abu-dhabi", "Abu Dhabi", "أبوظبي"], ["sharjah", "Sharjah", "الشارقة"]],
  QA: [["doha", "Doha", "الدوحة"]], KW: [["kuwait-city", "Kuwait City", "الكويت"]], BH: [["manama", "Manama", "المنامة"]],
  OM: [["muscat", "Muscat", "مسقط"]], EG: [["cairo", "Cairo", "القاهرة"], ["alexandria", "Alexandria", "الإسكندرية"]],
  JO: [["amman", "Amman", "عمّان"]], LB: [["beirut", "Beirut", "بيروت"]], IQ: [["baghdad", "Baghdad", "بغداد"]],
  MA: [["casablanca", "Casablanca", "الدار البيضاء"]], TR: [["istanbul", "Istanbul", "إسطنبول"]],
  GB: [["london", "London", "لندن"]], US: [["new-york", "New York", "نيويورك"]], DE: [["berlin", "Berlin", "برلين"]],
  FR: [["paris", "Paris", "باريس"]],
};
export const STATUSES = ["saved", "preparing", "applied", "interview", "offer", "rejected", "ghosted"];
export const STATUS_LABEL = { saved: "Saved", preparing: "Preparing", applied: "Applied", interview: "Interview", offer: "Offer", rejected: "Rejected", ghosted: "Ghosted" };
export const STATUS_DOT = { saved: "bg-slate-400", preparing: "bg-sky-500", applied: "bg-emerald-600", interview: "bg-amber-500", offer: "bg-emerald-800", rejected: "bg-rose-500", ghosted: "bg-slate-300" };
export const countryName = (code, lang) => {
  const c = COUNTRIES.find((x) => x[0] === code);
  return c ? (lang === "ar" ? c[2] : c[1]) : code || "";
};
